//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantSharp.SanmarkSolutions.MerchantSharpApp.Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MerchantSharp.SanmarkSolutions.MerchantSharpApp.Common.Messages.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Connect to Database..
        /// </summary>
        internal static string Error001 {
            get {
                return ResourceManager.GetString("Error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Backup Location is not set..
        /// </summary>
        internal static string Error002 {
            get {
                return ResourceManager.GetString("Error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account has been disabled..
        /// </summary>
        internal static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Item..
        /// </summary>
        internal static string Error004 {
            get {
                return ResourceManager.GetString("Error004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter basic details..
        /// </summary>
        internal static string Error005 {
            get {
                return ResourceManager.GetString("Error005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Price..
        /// </summary>
        internal static string Error006 {
            get {
                return ResourceManager.GetString("Error006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dublicate Entry..
        /// </summary>
        internal static string Error007 {
            get {
                return ResourceManager.GetString("Error007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Item.
        /// </summary>
        internal static string Error008 {
            get {
                return ResourceManager.GetString("Error008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row..
        /// </summary>
        internal static string Error009 {
            get {
                return ResourceManager.GetString("Error009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission to perform this action..
        /// </summary>
        internal static string Error010 {
            get {
                return ResourceManager.GetString("Error010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter cash amount..
        /// </summary>
        internal static string Error011 {
            get {
                return ResourceManager.GetString("Error011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add Items..
        /// </summary>
        internal static string Error012 {
            get {
                return ResourceManager.GetString("Error012", resourceCulture);
            }
        }
    }
}
