//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantSharp.SanmarkSolutions.MerchantSharpApp.Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Information {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Information() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MerchantSharp.SanmarkSolutions.MerchantSharpApp.Common.Messages.Information", typeof(Information).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Database....
        /// </summary>
        internal static string Info001 {
            get {
                return ResourceManager.GetString("Info001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string Info002 {
            get {
                return ResourceManager.GetString("Info002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Backup Location....
        /// </summary>
        internal static string Info003 {
            get {
                return ResourceManager.GetString("Info003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Backups....
        /// </summary>
        internal static string Info004 {
            get {
                return ResourceManager.GetString("Info004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backuping Database....
        /// </summary>
        internal static string Info005 {
            get {
                return ResourceManager.GetString("Info005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Backuped..
        /// </summary>
        internal static string Info006 {
            get {
                return ResourceManager.GetString("Info006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Meta....
        /// </summary>
        internal static string Info007 {
            get {
                return ResourceManager.GetString("Info007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded..
        /// </summary>
        internal static string Info008 {
            get {
                return ResourceManager.GetString("Info008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking License....
        /// </summary>
        internal static string Info009 {
            get {
                return ResourceManager.GetString("Info009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial has been expired..
        /// </summary>
        internal static string Info010 {
            get {
                return ResourceManager.GetString("Info010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trials Left.
        /// </summary>
        internal static string Info011 {
            get {
                return ResourceManager.GetString("Info011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Preferences....
        /// </summary>
        internal static string Info012 {
            get {
                return ResourceManager.GetString("Info012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Info013 {
            get {
                return ResourceManager.GetString("Info013", resourceCulture);
            }
        }
    }
}
